apiVersion: v1
kind: Service
metadata:
  name: deploy-uat-tomcat
  labels:
    app: deploy-uat-tomcat
spec:
  type: NodePort
  selector:
    app: deploy-uat-tomcat
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30001
