apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-qa-tomcat
  labels:
    app: deploy-qa-tomcat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deploy-qa-tomcat
  template:
    metadata:
      labels:
        app: deploy-qa-tomcat
    spec:
      containers:
      - name: container-qa-tomcat
        image: master-tomcat:v0.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: tz-config
          mountPath: /etc/localtime
        - name: test
          mountPath: /tmp
      volumes:
      - name: tz-config
        hostPath:
          path: /usr/share/zoneinfo/Asia/Shanghai
      - name: test
        hostPath:
          path: /tmp/
