apiVersion: v1
kind: Service
metadata:
  name: deploy-qa-tomcat
  labels:
    app: deploy-qa-tomcat
spec:
  type: NodePort
  selector:
    app: deploy-qa-tomcat
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30000
