#!groovy

node {
  try{
    timestamps{
       
    env.BRANCH_NAME
	sh 'echo branch: $BRANCH_NAME'
    
    env.deploy_submitter = 'xianke9'
	
    // if master branch
    if(env.BRANCH_NAME == 'master'){
            
      stage('git checkout') {
          git branch: 'master', credentialsId: 'ce591e8b-bf0a-41e4-a679-6f8082efa93c', url: 'http://itaasgitlab.cn.ibm.com/zzhifeng/docker-ci.git'
      }
   
      stage('maven build') {
          sh 'mvn -version'
          sh 'mvn -Dmaven.test.failure.ignore clean install -U' 
      }
      
      stage('build docker image') {
          sh 'echo job name: $JOB_NAME build_number: $BUILD_NUMBER'      

sh '''cat <<EOF > Dockerfile
FROM 9.111.212.224/library/tomcat:7.0
ADD ./target/demo.war /usr/local/tomcat/webapps/
RUN echo "Asia/Shanghai" > /etc/timezone
RUN dpkg-reconfigure -f noninteractive tzdata
EOF'''
      }
      
      // do deployment to QA env
      stage ('Deploy to QA'){
        //input message: 'Are you sure to deploy to QA',
        //ok: 'Depoly',
        //submitter: "${deploy_submitter}"
          echo 'Deploy to QA'
          deployToQA()
          sh 'echo QA env URL: http://qa.zzhifeng.com/demo' 		 
      }	
    
   }
  }    
  }catch(err){
       throw err
   }
 }
 


def deployToQA(){ 
    env.imageTag = 'master'  
    env.envTag   = 'qa'
    
    sh 'echo deploy to QA env .........'
    
    sh 'docker -H tcp://9.111.213.236:4000 build --rm -t 9.111.212.224/library/$imageTag-tomcat:v$BUILD_NUMBER .'
    sh 'docker -H tcp://9.111.213.236:4000 login -u zzhifeng -p Passw0rd -e \"zzhifeng@cn.ibm.com\" 9.111.212.224'
    sh 'docker -H tcp://9.111.213.236:4000 push 9.111.212.224/library/$imageTag-tomcat:v$BUILD_NUMBER'

    sh 'echo rolling update'
    sh 'sshpass -p "#noPassw0rd" ssh -o StrictHostKeyChecking=no root@9.110.85.100 "kubectl set image deploy/deploy-$envTag-tomcat container-$envTag-tomcat=9.111.212.224/library/$imageTag-tomcat:v$BUILD_NUMBER"'
	  
    sh 'sshpass -p "#noPassw0rd" ssh -o StrictHostKeyChecking=no root@9.110.85.100 "kubectl rollout status deploy/deploy-$envTag-tomcat"'
    
}


